import { Hono } from "hono";
import { accountRoutes } from "./accounts.ts";
import { authRoutes } from "./auth.ts";
import { inboxRoutes } from "./inboxes.ts";
import { contactRoutes } from "./contacts.ts";
import { conversationRoutes } from "./conversations.ts";
import { messageRoutes } from "./messages.ts";
import { labelRoutes } from "./labels.ts";
import { widgetRoutes } from "./widget.ts";
import { attachmentRoutes } from "./attachments.ts";
import { teamRoutes } from "./teams.ts";
import { typingRoutes } from "./typing.ts";
import { offlineMessageRoutes } from "./offlineMessages.ts";
import { cannedResponseRoutes } from "./cannedResponses.ts";
import { auditLogRoutes } from "./auditLogs.ts";
import { analyticsRoutes } from "./analytics.ts";
import { gdprRoutes } from "./gdpr.ts";
import { webhookRoutes } from "./webhooks.ts";
import { aiRoutes } from "./ai.ts";
import { pushRoutes } from "./push.ts";
import { automationRoutes } from "./automation.ts";
import { integrationRoutes } from "./integrations.ts";
import { rbacRoutes } from "./roles.ts";
import { trackingRoutes, crmTrackingRoutes } from "./tracking.ts";
import { slaRoutes } from "./sla.ts";
import { auditLoggerMiddleware } from "@/middleware/auditLogger.ts";

const v1Routes = new Hono();

v1Routes.use("*", auditLoggerMiddleware);

v1Routes.route("/accounts", accountRoutes);
v1Routes.route("/auth", authRoutes);
v1Routes.route("/inboxes", inboxRoutes);
v1Routes.route("/contacts", contactRoutes);
v1Routes.route("/contacts/:id/conversations", widgetRoutes);
v1Routes.route("/conversations", conversationRoutes);
v1Routes.route("/conversations", labelRoutes);
v1Routes.route("/conversations/:conversation_id/messages", messageRoutes);
v1Routes.route("/messages", messageRoutes);
v1Routes.route("/labels", labelRoutes);
v1Routes.route("/attachments", attachmentRoutes);
v1Routes.route("/teams", teamRoutes);
v1Routes.route("/conversations/:id/typing", typingRoutes);
v1Routes.route("/offline-messages", offlineMessageRoutes);
v1Routes.route("/canned-responses", cannedResponseRoutes);
v1Routes.route("/audit-logs", auditLogRoutes);
v1Routes.route("/analytics", analyticsRoutes);
v1Routes.route("/gdpr", gdprRoutes);
v1Routes.route("/webhooks", webhookRoutes);
v1Routes.route("/conversations", aiRoutes);
v1Routes.route("/push", pushRoutes);
v1Routes.route("/automation", automationRoutes);
v1Routes.route("/integrations", integrationRoutes);
v1Routes.route("/roles", rbacRoutes);
v1Routes.route("/tracking", trackingRoutes);
v1Routes.route("/tracking", crmTrackingRoutes);
v1Routes.route("/sla", slaRoutes);

export { v1Routes };
